---

- hosts: all
  become: true
  tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: controller
  become: true
  roles:
    - Keystone
    - Glance

- hosts: compute
  become: true
  roles:
    - Nova
